import { ArrowRight, Check, HandHelping, MapPin, Megaphone, MessageCircle, Package, Search, Sparkles, Store, Wrench } from "lucide-react"
import { LandingAuthLink } from "./landing-auth-link"

const modules = [
  { title: "Necesidades", copy: "Publicá lo que buscás y convertí una búsqueda sin resultados en demanda.", icon: HandHelping, accent: "border-[#FF5A67] text-[#b42336]" },
  { title: "Servicios", copy: "Encontrá especialistas por rubro y zona, o respondé oportunidades.", icon: Wrench, accent: "border-blue-500 text-blue-700" },
  { title: "Comercios", copy: "Negocios con ubicación, horarios, catálogo, atención y pedidos.", icon: Store, accent: "border-teal-500 text-teal-700" },
  { title: "Emprendimientos", copy: "Marcas locales, producción propia, encargos y entregas coordinadas.", icon: Sparkles, accent: "border-violet-500 text-violet-700" },
]
const searches = ["electricista", "torta personalizada", "alimento balanceado", "farmacia", "profesora de matemática", "decoración", "ferretería"]

export function LandingFeatures() {
  return <>
    <section id="como-funciona" className="bg-background py-20"><div className="mx-auto max-w-6xl px-5 sm:px-6">
      <p className="text-xs font-bold uppercase tracking-[.16em] text-[#b42336]">Dos lados, una misma red</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-5xl">Quien busca encuentra. Quien ofrece, crece.</h2>
      <div className="mt-10 grid gap-4 lg:grid-cols-2">
        <article className="rounded-[2rem] bg-white p-7 ring-1 ring-slate-900/10"><Search className="h-7 w-7 text-[#FF5A67]"/><h3 className="mt-8 text-2xl font-black">Busco cerca</h3><ul className="mt-5 grid gap-3 text-sm text-slate-600 sm:grid-cols-2">{["Encontrar servicios", "Descubrir comercios", "Ver productos", "Armar pedidos", "Contactar por WhatsApp", "Publicar necesidades"].map(x=><li key={x} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-[#FF5A67]"/>{x}</li>)}</ul></article>
        <article className="rounded-[2rem] bg-vezi-ink p-7 text-white"><Store className="h-7 w-7 text-[#FF7C87]"/><h3 className="mt-8 text-2xl font-black">Ofrezco en mi zona</h3><ul className="mt-5 grid gap-3 text-sm text-slate-300 sm:grid-cols-2">{["Crear mi perfil", "Publicar servicios", "Subir mi catálogo", "Aparecer en búsquedas", "Recibir consultas", "Recibir pedidos"].map(x=><li key={x} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-[#FF7C87]"/>{x}</li>)}</ul></article>
      </div>
    </div></section>

    <section className="bg-vezi-ink py-20 text-white"><div className="mx-auto grid max-w-6xl gap-10 px-5 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#FF7C87]">La búsqueda es la puerta</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Encontrá lo que necesitás.</h2><p className="mt-4 text-slate-300">Una sola búsqueda reúne Servicios, Comercios, Emprendimientos y Productos relevantes cerca tuyo.</p><div className="mt-6 flex flex-wrap gap-2">{searches.map(x=><span key={x} className="rounded-full border border-white/15 px-3 py-2 text-xs text-slate-300">{x}</span>)}</div></div>
      <div className="rounded-[2rem] bg-background p-4 text-slate-950 sm:p-6"><div className="flex items-center gap-3 rounded-2xl bg-white p-4 shadow-sm"><Search className="h-5 w-5 text-[#FF5A67]"/><span className="font-bold">torta personalizada</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border-l-4 border-emerald-500 bg-white p-4"><b>Azúcar Estudio</b><p className="text-xs text-slate-500">Emprendimiento · 1,8 km</p></div><div className="rounded-2xl border-l-4 border-violet-500 bg-white p-4"><b>Torta chocolate 20 cm</b><p className="text-xs text-slate-500">Producto · $24.000</p></div></div><div className="mt-3 rounded-2xl border border-dashed border-amber-500 p-4 text-sm"><b>¿No aparece lo que buscás?</b><span className="ml-2 text-amber-800">Publicá una necesidad →</span></div></div>
    </div></section>

    <section id="para-negocios" className="bg-background py-20"><div className="mx-auto grid max-w-6xl gap-12 px-5 sm:px-6 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b42336]">Tu comercio o emprendimiento en VEZI</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Mucho más que un directorio.</h2><p className="mt-4 leading-relaxed text-slate-600">Un perfil completo con fotos, descripción, horarios, ubicación y contacto. Sumá productos con imágenes, precios y categorías para aparecer en búsquedas, módulos, novedades y recomendaciones.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{[[MapPin,"Perfil completo"],[Package,"Catálogo visible"],[Search,"Descubrimiento local"],[MessageCircle,"Pedido directo"]].map(([Icon,title])=>{const I=Icon as typeof MapPin;return <div key={String(title)} className="flex items-center gap-3 rounded-2xl bg-white p-4 font-bold ring-1 ring-slate-900/10"><I className="h-5 w-5 text-[#FF5A67]"/>{String(title)}</div>})}</div></div>
      <div className="rounded-[2rem] bg-white p-4 shadow-xl ring-1 ring-slate-900/10"><div className="rounded-2xl bg-vezi-ink p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs text-orange-300">Comercio · a 900 m</p><h3 className="mt-1 text-xl font-black">Almacén Don Carlos</h3></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">Abierto</span></div><p className="mt-3 text-sm text-slate-300">Productos de almacén y frescos · Lun–Sáb 8 a 20 h</p></div><p className="mb-3 mt-5 text-xs font-bold uppercase tracking-widest text-slate-500">Catálogo</p><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-background p-4"><div className="mb-8 h-16 rounded-xl bg-gradient-to-br from-[#FF5A67]/10 to-[#D81BFF]/10"/><b>Picada local</b><p className="text-sm text-slate-500">$18.500</p></div><div className="rounded-2xl bg-background p-4"><div className="mb-8 h-16 rounded-xl bg-gradient-to-br from-[#D81BFF]/10 to-[#FF5A67]/10"/><b>Pan artesanal</b><p className="text-sm text-slate-500">$4.200</p></div></div></div>
    </div></section>

    <section className="bg-vezi-ink py-20 text-white"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#FF7C87]">Sin cambiar tu operación</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Del producto a WhatsApp.</h2><p className="mt-4 text-slate-300">VEZI facilita el descubrimiento y el pedido. El negocio conserva su forma habitual de coordinar pago, retiro o entrega.</p></div><div className="grid gap-3 sm:grid-cols-4">{["1. Producto","2. Agregar al pedido","3. Pedido armado","4. Enviar por WhatsApp"].map((x,i)=><div key={x} className="relative rounded-2xl bg-white/8 p-5 text-sm font-bold ring-1 ring-white/10">{x}{i<3&&<ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-6 w-6 -translate-y-1/2 rounded-full bg-orange-500 p-1 sm:block"/>}</div>)}</div></div></div></section>

    <section className="bg-background py-20"><div className="mx-auto grid max-w-6xl gap-10 px-5 sm:px-6 lg:grid-cols-2 lg:items-center"><div className="rounded-[2rem] border border-amber-300 bg-white p-6"><p className="text-xs font-bold uppercase text-amber-700">Necesidad abierta · Hoy</p><p className="mt-5 text-xl font-black">“Necesito electricista para hoy.”</p><div className="mx-auto h-8 w-px bg-amber-300"/><div className="rounded-2xl bg-sky-50 p-4 text-sm"><b className="text-sky-800">Roberto puede ayudarte</b><p className="mt-1 text-slate-600">Electricista matriculado · Respondió hace 5 min</p></div></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700">El diferencial VEZI</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">¿No lo encontraste?</h2><p className="mt-4 text-slate-600">Publicá lo que necesitás. VEZI puede acercar esa necesidad a perfiles relevantes y transformar una búsqueda sin resultado en una oportunidad local.</p></div></div></section>

    <section id="modulos" className="bg-background pb-20"><div className="mx-auto max-w-6xl px-5 sm:px-6"><h2 className="text-3xl font-black sm:text-5xl">Cuatro módulos. Una sola VEZI.</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{modules.map(({title,copy,icon:Icon,accent})=><article key={title} className={`rounded-3xl border-t-4 bg-white p-6 shadow-sm ${accent}`}><Icon className="h-6 w-6"/><h3 className="mt-10 text-xl font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{copy}</p></article>)}</div></div></section>

    <section className="bg-white py-20"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-4 md:grid-cols-3">{[[Wrench,"Ofrezco un servicio","Especialidad, zona, consultas y respuestas a necesidades.","service"],[Store,"Tengo un comercio","Ubicación, horarios, catálogo, atención y pedidos.","commerce"],[Sparkles,"Tengo un emprendimiento","Producción propia, encargos y entregas coordinadas.","venture"]].map(([Icon,title,copy,intent])=>{const I=Icon as typeof Wrench;return <article key={String(title)} className="rounded-3xl bg-background p-6"><I className="h-6 w-6 text-[#FF5A67]"/><h3 className="mt-8 text-xl font-black">{String(title)}</h3><p className="mt-2 min-h-12 text-sm text-slate-600">{String(copy)}</p><LandingAuthLink intent={intent as "service"|"commerce"|"venture"} className="mt-6 inline-flex items-center gap-2 font-bold">Crear mi perfil <ArrowRight className="h-4 w-4"/></LandingAuthLink></article>})}</div></div></section>

    <section id="novedades" className="bg-background py-20"><div className="mx-auto grid max-w-6xl gap-8 px-5 sm:px-6 lg:grid-cols-[.7fr_1.3fr]"><div><Megaphone className="h-7 w-7 text-[#FF5A67]"/><h2 className="mt-5 text-3xl font-black sm:text-5xl">El pulso de tu zona.</h2><p className="mt-3 text-slate-600">Aperturas, promociones, recomendaciones y actividad reciente.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl bg-white p-5 ring-1 ring-slate-900/10"><b>Nuevo cerca</b><p className="mt-2 text-sm text-slate-600">Abrió una cafetería de especialidad en Hudson.</p></div><div className="rounded-3xl bg-vezi-ink p-5 text-white"><b>Pedido enviado</b><p className="mt-2 text-sm text-slate-300">Una vecina armó su pedido y contactó al negocio por WhatsApp.</p></div></div></div></section>
  </>
}
